name = "scdemos-feed"
main = "index.js"
compatibility_date = "2026-02-16"

[vars]
SITE_URL = "https://diyfire.ca"
CONTENT_ORIGIN = "https://main--demo--scdemos.aem.live"

[observability.logs]
enabled = true
